<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE applications [
<!ELEMENT applications (application)+>
<!ELEMENT application (studentId , projectId)>
<!ELEMENT studentId (#PCDATA)>
<!ELEMENT projectId (#PCDATA)>
]>
<applications>
    
    <application>
        <studentId>4</studentId>
        <projectId>0</projectId>
    </application>
    <application>
        <studentId>1</studentId>
        <projectId>0</projectId>
    </application>
</applications>
